---
common_commands: []
#  - clr
#  - dmesg-custom
#  - l
#  - la
#  - ll
#  - mount-custom
#  - o
#  - oo
#  - p
#  - path-custom
#  - pp
#  - ss
common_commands_group: root
common_commands_user: root
common_files_path: ../../files/common/
common_host_domain: .lan
common_host_env: .dev
common_host_externals: []
#  - 127.0.0.1       adserver.domain.com
common_host_internals: {}
#  192.168.1.1:      router
common_host_ip: 127.0.0.1
common_host_websites: []
#  - default
common_locale_name: false # en_US.UTF-8
common_remote_path: /usr/local/bin/
common_required_libraries:
  - aptitude
  - debconf
  - debconf-utils
  - python-apt
common_required_packages:
  - curl
  - python-software-properties
  - software-properties-common
common_timezone_name: false # GMT+0
