---
common_commands: []
#  - clr
#  - dmesg-custom
#  - l
#  - la
#  - ll
#  - mount-custom
#  - o
#  - oo
#  - p
#  - path-custom
#  - pp
#  - ss
common_commands_group: root
common_commands_user: root
common_files_path: ../../files/common/
common_host_domain: .lan
common_host_env: .dev
common_host_externals: {}
#  127.0.0.1: adserver.domain.com   # => 127.0.0.1      adserver.domain.com
common_host_internals: {}
#  192.168.1.1: router              # => 192.168.1.1    router              router.lan
common_host_websites: {}
#  192.168.1.100: projectx          # => 192.168.1.100  projectx.dev.lan    www.projectx.dev.lan
common_host_websites_ip: 192.168.1.200
common_host_websites_without_ip: []
#  - projecty                       # => 192.168.1.200  projecty.dev.lan    www.projecty.dev.lan
common_locale_name: false # en_US.UTF-8
common_remote_path: /usr/local/bin/
common_timezone_name: false # GMT+0
