---
common_commands: []
#  - dmesg-show
#  - mount-show
#  - o
#  - oo
#  - p
#  - path-show
#  - pp
#  - ss
common_commands_group: ~
common_commands_user: ~
common_files_path: ../../files/common/
common_host_domain: .lan
common_host_env: .dev
common_host_externals: {}
#  127.0.0.1: adserver.domain.com   # => 127.0.0.1      adserver.domain.com
common_host_internals: {}
#  192.168.1.1: router              # => 192.168.1.1    router              router.lan
common_host_websites: {}
#  192.168.1.100: project_x         # => 192.168.1.100  project_x.dev.lan    www.project_x.dev.lan
common_host_websites_ip: 192.168.1.200
common_host_websites_without_ip: []
#  - project_y                      # => 192.168.1.200  project_y.dev.lan    www.project_y.dev.lan
common_locale_name: false # en_US.UTF-8
common_remote_path: ~/bin/ # OR /usr/local/bin/
common_timezone_name: false # GMT+0
