---
common_commands: []
#  - clr
#  - l
#  - mounts
#  - o
#  - oo
#  - p
#  - paths
#  - pp
common_files_path: ../../files/common/
common_locales_name: en_US.UTF-8
common_remote_path: /usr/local/bin/
common_required_packages:
  - curl
  - python-software-properties
  - software-properties-common
