---
virtualbox_key_id: 98AB5139
virtualbox_key_url: http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
virtualbox_repository: deb http://download.virtualbox.org/virtualbox/debian wheezy contrib
