---
- include: avahi.yml
  when: "'avahi' in fix_issues"

- include: blkid_tab.yml
  when: "'blkid-tab' in fix_issues"

- include: bluetooth.yml
  when: "'bluetooth' in fix_issues"

- include: brightness.yml
  when: "'brightness' in fix_issues"

- include: inotify.yml
  when: "'inotify' in fix_issues"
