---
- name: install tool
  shell: >
    /usr/bin/curl -sS http://static.phpmd.org/php/{{ phpmd_version }}/phpmd.phar -o phpmd.phar &&
    /bin/mv phpmd.phar {{ phpmd_path }}
    creates="{{ phpmd_path }}"

- name: allow everyone for selfupdate
  file: >
    group=root
    mode="0777"
    owner=root
    path="{{ phpmd_path }}"
