---
vagrant_allow_hosts: []
#  - "rpcbind mountd nfsd statd lockd rquotad : 192.168.50."
vagrant_deny_hosts: []
#  - "rpcbind mountd nfsd statd lockd rquotad : ALL"
vagrant_modules:
  - nfs-common
  - nfs-kernel-server
vagrant_nfs_lines: {}
#  Default-Start: ""
#  Default-Stop  "0 1 2 3 4 5 6"
vagrant_plugins:
  - vagrant-vbguest
vagrant_rpc_mountd_port: 1011
vagrant_vagrant_path: /usr/bin/vagrant
vagrant_version: 1.7.0
vagrant_sudoers_path: /etc/sudoers.d
