---
- name: install tool
  shell: >
    /usr/bin/curl -sS https://phar.phpunit.de/phploc.phar -o phploc.phar &&
    /bin/mv phploc.phar {{ phploc_path }}
    creates="{{ phploc_path }}"

- name: allow everyone for selfupdate
  file: >
    group=root
    mode="0777"
    owner=root
    path="{{ phploc_path }}"
