---
wkhtmltox_pre_packages:
  - fontconfig
  - libc6
  - libfontconfig1
  - libfreetype6
  - libjpeg8
  - libpng12-0
  - libssl1.0.0
  - libstdc++6
  - libx11-6
  - libxext6
  - libxrender1
  - xfonts-75dpi
  - xfonts-base
  - zlib1g
wkhtmltox_url: http://download.gna.org/wkhtmltopdf/0.12/{{ wkhtmltox_version }}/wkhtmltox-{{ wkhtmltox_version }}_linux-wheezy-amd64.deb
