---
- name: install required libraries
  homebrew: >
    name="{{ item }}"
    state=present
  with_items: common_required_libraries

- name: install required packages
  homebrew: >
    name="{{ item }}"
    state=present
  with_items: common_required_packages
