---
php_configs:
  apache: false
  cli: false
  common: false
  environment: false
  project: false
php_files_path: ../../files/php/
php_modules:
  - php5-cli
  - php5-common
#  - php5-curl
#  - php5-gd
#  - php5-imagick=3.*
#  - php5-imap
#  - php5-intl
#  - php5-mbstring  # built-in
#  - php5-mcrypt
#  - php5-readline
#  - php5-xsl

#  - php-amqplib
#  - php5-memcached=2.*
#  - php5-mongo=1.*
#  - php5-mysqlnd
#  - php5-pgsql
#  - php5-redis=2.*
#  - php5-sqlite
php_version: 5.6
